use sql_airbnb;
SHOW tables;
DESCRIBE accommodation;

SELECT table_name, table_type, engine
FROM information_schema.tables
WHERE table_schema = 'sql_airbnb';
ORDER BY table_name;

SELECT
    TABLE_NAME, ENGINE, VERSION, ROW_FORMAT, TABLE_ROWS, AVG_ROW_LENGTH,
    DATA_LENGTH, MAX_DATA_LENGTH, INDEX_LENGTH, DATA_FREE, AUTO_INCREMENT,
    CREATE_TIME, UPDATE_TIME, CHECK_TIME, TABLE_COLLATION, CHECKSUM,
    CREATE_OPTIONS, TABLE_COMMENT
  FROM INFORMATION_SCHEMA.TABLES
  WHERE table_schema = 'sql_airbnb';

SHOW TABLE STATUS
  FROM sql_airbnb;
